# Generated by Django 4.0.3 on 2023-03-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_rename_month_monthreport_monthwise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthreport',
            old_name='monthwise',
            new_name='month',
        ),
    ]
